version: '3.8'

services:
  perfex:
    build: .
    image: perfex
    depends_on:
      - mysql
    ports:
      - "8081:80"
    volumes:
      - perfex_data:/var/www/html/
    labels:
      - "coolify.enable=true"

  mysql:
    image: mysql:8.4
    restart: always
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: yourStrongRootPassword
      MYSQL_DATABASE: perfex
      MYSQL_USER: perfexuser
      MYSQL_PASSWORD: perfexpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  perfex_data:
    driver: local
  mysql_data:
    driver: local
